### ISSUE TITLE
Include scroll support

### ISSUE THREAD

**Issue by robertsanseries** [bartzaalberg/php-tester#11]
Currently, it is not possible to test large codes.

![php-tester](https://user-images.githubusercontent.com/11967501/32618629-04c450e0-c557-11e7-9f75-74bb2894c274.png)

Use the `Gtk.ScrolledWindow` to resolve this problem.

![Gtk.ScrolledWindow](https://valadoc.org/gtk+-3.0/img/example-Gtk.ScrolledWindow.png)

Documentation of the component in the valadoc: https://valadoc.org/gtk+-3.0/Gtk.ScrolledWindow.html

**Comment by bartzaalberg** [comment]
Fixed. Is added to next release. Please let me know if your are still experiencing this after the update.

**Comment by robertsanseries** [comment]
Thank you! : D

Many thanks for your application! #Loved it
