### ISSUE TITLE
Add support for translation

### ISSUE THREAD

**Issue by robertsanseries** [bartzaalberg/php-tester#12]
I would like to translate your app into Portuguese from Brazil!

Note: Also add string translation to the AppCenter.

**Comment by DataRot** [comment]
Installed from app center pair the 1.00. After install the app will run but says there is no php versions installed ? How to install the PHP version I will use ?

**Comment by robertsanseries** [comment]
@DataRot you should create a separate issue for your problem!

**Comment by robertsanseries** [comment]
@bartzaalberg I'll check the translation settings this week

**Comment by bartzaalberg** [comment]
I added support for translations to master. Good luck!
