### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by blackfiles** [bartzaalberg/php-tester#13]
when i try to run the code i get this alert

> An error occured
> Failed to execute child process "/usr/bin/php7.1" (No such file or directory)

**Comment by bartzaalberg** [comment]
Ok, and what happens if you run php7.1 in your command line?

**Comment by robertsanseries** [comment]
@bartzaalberg  Output command line:

```
Command 'php7.1' not found, did you mean:
  'Php7.0-cli' (main) package 'php7.0' command
php7.1: command not found
```

![captura de tela de 2017-11-17 00-34-20](https://user-images.githubusercontent.com/11967501/32928106-1e38e4cc-cb2f-11e7-8f7e-a7e90ffa3397.png)

**Comment by bartzaalberg** [comment]
Ok, so that doesn't work either. How do you normally run php in the terminal? And what do you get when running the following command? `ll /usr/bin | grep php` Because that's where i check for PHP versions.

**Comment by robertsanseries** [comment]
```
robertsanseries@robert-desktop:~$ ll /usr/bin | grep php
-rwxr-xr-x  1 root            root               52600 Nov 10 10:08 com.github.bartzaalberg.php-tester*
-rwxr-xr-x  1 root            root                2257 Mar 24  2016 jsonlint-php*
lrwxrwxrwx  1 root            root                  21 Out 26 14:40 php -> /etc/alternatives/php*
-rwxr-xr-x  1 root            root             4430896 Ago  9 11:43 php7.0*

```

**Comment by bartzaalberg** [comment]
So you actually have the php7.0. But when you call it you get an error? Because that's not an app related problem. php7.0 should give valid php output.

**Comment by robertsanseries** [comment]
@bartzaalberg  I'm sorry for the late reply!

* Yes, I have PHP7

* There is no failure to run php via terminal.

* I believe the application should adapt to the new settings of php7.

**Comment by bartzaalberg** [comment]
The application already supports php7. Must be another problem. Will look into it later.

Op 23 dec. 2017 03:01 schreef Robert San <notifications@github.com>:

@bartzaalberg<https://github.com/bartzaalberg> I'm sorry for the late reply!

  *   Yes, I have PHP7

  *   There is no failure to run php via terminal.

  *   I believe the application should adapt to the new settings of php7.

**Comment by jonnps** [comment]
The app is looking for /usr/bin/php7.1 when only php7.0 is installed.

If i just copy the file php7.0 and rename to php7.1 works.

**Comment by bartzaalberg** [comment]
Ah that is a problem indeed. Will retry

**Comment by bartzaalberg** [comment]
I committed a fix. Hope this works! Sorry it took so long. I didn't have a alot of time lately

**Comment by bartzaalberg** [comment]
Fix is now live. Problem shouldn't occur anymore. You may need to reinstall the application. Please close this issue if the fix works for you.

**Comment by bartzaalberg** [comment]
Closing this as there is no comment
