### ISSUE TITLE
Elementary OS - No scroll bar

### ISSUE THREAD

**Issue by kurtr** [bartzaalberg/php-tester#14]
Using v1.5 on elementary os no scroll bar appears when typing/pasting a long string into the editor, instead the window resizes out of the view port.

**Comment by bartzaalberg** [comment]
Are you sure you are using 1.5?..

**Comment by kurtr** [comment]
100%
![screenshot from 2017-11-22 03 24 22](https://user-images.githubusercontent.com/1468721/33105216-c723ff5a-cf34-11e7-950d-d928b6e10e99.png)

**Comment by bartzaalberg** [comment]
Oh like that! Will fix that.

Op 22 nov. 2017 02:25 schreef kurtr <notifications@github.com>:

100%
[screenshot from 2017-11-22 03 24 22]<https://user-images.githubusercontent.com/1468721/33105216-c723ff5a-cf34-11e7-950d-d928b6e10e99.png>

**Comment by bartzaalberg** [comment]
Fixed in release 1.5.1
