### ISSUE TITLE
ERROR: Failed to execute child process

### ISSUE THREAD

**Issue by spekulatius** [bartzaalberg/php-tester#15]
![image](https://user-images.githubusercontent.com/8433587/34148018-ae66c810-e4da-11e7-8473-0dea8eebefd5.png)

Elementary 0.4.1

**Comment by robertsanseries** [comment]
The same error reported in Issue #13

**Comment by spekulatius** [comment]
Oh, I didn't check that before. Sorry.

**Comment by robertsanseries** [comment]
@spekulatius sorry, the information went to @bartzaalberg  LoL

**Comment by spekulatius** [comment]
All good :)
