### ISSUE TITLE
could you make a flatpak for php-tester?

### ISSUE THREAD

**Issue by chemel9** [bartzaalberg/php-tester#16]
Hi, I really appreciate your work , is a good application
but i don't use elementary OS
could you make a flatpak for php-tester?
in this way, users can install the application in any linux distribution

please.
thank you.

**Comment by bartzaalberg** [comment]
When i got some time on my hands i may try this. At the moment this isn't priority to me.

**Comment by bartzaalberg** [comment]
Ok, so i made a branch which i actually managed to get to work. But i need to get the php executables from my root dir. Which of course the flatpak can't find. Have you got any experience with this?

**Comment by bartzaalberg** [comment]
I'm sorry this takes to much time which is don't have. I don't want to focus on this, as i am building the app for ElementaryOS. Closing this.
