### ISSUE TITLE
Strange halt

### ISSUE THREAD

**Issue by pavlepiramida** [bartzaalberg/php-tester#17]
Strange thing is happening,
If you dont have any php installed and you try to run php-tester, desktop(environment) freezes after launch.
I encountered it first on Arch after compiling your app from scratch,and today on fresh install of Loki.

You literally cant do jack in this situation.
Only way to regain back control is to tty out and kill running instances of the app...

First I thought it was a mutter issue,but now seeing that its also happening on gala and elementary I kinda wonder whats going on.

If there's any way for me to better debug this and help,do tell,Im all ears!

**Comment by bartzaalberg** [comment]
Odd, i will look into this when i have some spare time.

**Comment by selwynorren** [comment]
Hmm I have the same issue. I have xampp installed so I definitely have php installed, but after launch it says I don't have any php installed at all, and I can seem to configure the php location

**Comment by bartzaalberg** [comment]
@selwynorren that sounds like a completely different issue.

**Comment by selwynorren** [comment]
Thanks @bartzaalberg I can believe so, although I experience the exact same symptom. Everything Freezes and I cannot select anything. Is there a way I can provide debug information for you? I really love what this app can apparently do

**Comment by selwynorren** [comment]
No Problem at all, I appreciate your willingness to help here

**Comment by bartzaalberg** [comment]
Hi! I fixed a fatal error which happens on startup when PHP is not found. Maybe this caused the problem for you. Could you try the app again if 1.6.0 is released and see if it still happens?

**Comment by selwynorren** [comment]
Thanks, I still get the same condition if I click on the copy icon, however the php location issue I have commented on in another post, but the app now no longer has the same effect of disallowing inputs. Thanks so much for all your efforts

**Comment by bartzaalberg** [comment]
Ok, so can this issue be closed?

**Comment by selwynorren** [comment]
I am not entirely sure to be honest. Even though now I can click on the setting icon, if I click on any other icon, then I have the same condition.

**Comment by bartzaalberg** [comment]
Yes but the other icons should only work when php is actually loaded.  They should be greyed out right?

**Comment by selwynorren** [comment]
They are indeed greyed out, however you can still click on them, so in this case even though php cannot be found, I can still click the copy input and copy output. When this happens the who system freezes, however I can click the close button when exits the app and then my system returns to normal. I can also click the gear icon and that all works. Unfortunately due to the fact the screen freezes, I cannot even launch the screenshot app to take a screenshot to show you

**Comment by bartzaalberg** [comment]
Ok if i understand correctly. Clicking on one of the greyed out icons causes everything outside of the application to freeze. Because afterwards you could still click the gear icon. Correct?

**Comment by selwynorren** [comment]
Yes 100% correct

**Comment by bartzaalberg** [comment]
Thnx for the info!

**Comment by selwynorren** [comment]
> Thnx for the info!

Absolute pleasure, shout if I can test or be of any type of assistance. I am trying to learn vala, but I cant seem to wrap my head around it yet, so I cant hep there - lol but I can test and provide feedback

**Comment by bartzaalberg** [comment]
Ok, so the crash apparently only happended when i opened the copy input and copy output menu. I made sure that when everything else is disabled. That menu cant be opened. So the crash shouldn't happen anymore in the next release.

**Comment by bartzaalberg** [comment]
Its been released. Can you test?

**Comment by selwynorren** [comment]
Absolutely perfect, thank you so much for your efforts and hard work. I can confirm it works 100% correct
