### ISSUE TITLE
Add settings, to change php path

### ISSUE THREAD

**Issue by dignityinside** [bartzaalberg/php-tester#19]
I have xampp installed so I definitely have php installed, but after launch it says I don't have any php installed at all, and I can seem to configure the php location

_Originally posted by @selwynorren in https://github.com/bartzaalberg/php-tester/issues/17#issuecomment-442743637_

Please add settings, to change php path.

**Comment by selwynorren** [comment]
Hi, this is what I am saying and what my comment was on the previous post. We cannot do that. If I click on the gear it renders all input on my system impossible, both keyboard and mouse inputs. I have to quit your app, just to be able to access any other app on the system. The preferences are greyed out and I cannot click on a single thing, anywhere

**Comment by bartzaalberg** [comment]
I added it to the latest release! Hope it works for you.

**Comment by bartzaalberg** [comment]
No, it checks for all the php executables in that directory. Whats it called? Could you send the result of 'ls -l /opt/lampp/lib' ?

**Comment by selwynorren** [comment]
Yeah sure, bellow is the output for you

selwynorren@XXXXXXXXX:~$ ls -l /opt/lampp/lib
total 45280
-rw-r--r--  1 root root     9262 Nov 15 00:09 apr.exp
drwxr-xr-x  2 root root     4096 Nov 27 13:18 apr-util-1
-rw-r--r--  1 root root     5549 Nov 15 00:09 aprutil.exp
-rw-r--r--  1 root root      251 Nov 15 00:00 charset.alias
drwxr-xr-x  3 root root     4096 Nov 27 13:17 cmake
drwxr-xr-x  2 root root     4096 Nov 27 13:17 engines
drwxr-xr-x  2 root root     4096 Nov 27 13:17 gettext
drwxr-xr-x  3 root root     4096 Nov 27 13:18 icu
lrwxrwxrwx  1 root root       24 Nov 27 13:18 instantclient -> instantclient-11.2.0.3.0
drwxr-xr-x  3 root root     4096 Nov 27 13:18 instantclient-11.2.0.3.0
lrwxrwxrwx  1 root root       15 Nov 27 13:18 libaio.so -> libaio.so.1.0.1
lrwxrwxrwx  1 root root       15 Nov 27 13:18 libaio.so.1 -> libaio.so.1.0.1
-rwxr-xr-x  1 root root     5448 Nov 15 00:40 libaio.so.1.0.1
lrwxrwxrwx  1 root root       17 Nov 27 13:18 libapr-1.so -> libapr-1.so.0.5.2
lrwxrwxrwx  1 root root       17 Nov 27 13:18 libapr-1.so.0 -> libapr-1.so.0.5.2
-rwxr-xr-x  1 root root   222680 Nov 15 00:40 libapr-1.so.0.5.2
lrwxrwxrwx  1 root root       18 Nov 27 13:18 libapreq2.so -> libapreq2.so.3.8.0
lrwxrwxrwx  1 root root       18 Nov 27 13:18 libapreq2.so.3 -> libapreq2.so.3.8.0
-rwxr-xr-x  1 root root    60168 Nov 15 00:40 libapreq2.so.3.8.0
lrwxrwxrwx  1 root root       21 Nov 27 13:18 libaprutil-1.so -> libaprutil-1.so.0.5.4
lrwxrwxrwx  1 root root       21 Nov 27 13:18 libaprutil-1.so.0 -> libaprutil-1.so.0.5.4
-rwxr-xr-x  1 root root   176656 Nov 15 00:41 libaprutil-1.so.0.5.4
lrwxrwxrwx  1 root root       15 Nov 27 13:18 libbz2.so -> libbz2.so.1.0.2
lrwxrwxrwx  1 root root       15 Nov 27 13:18 libbz2.so.1 -> libbz2.so.1.0.2
-rwxr-xr-x  1 root root    66880 Nov 15 00:40 libbz2.so.1.0.2
lrwxrwxrwx  1 root root       19 Nov 27 13:18 libcharset.so -> libcharset.so.1.0.0
lrwxrwxrwx  1 root root       19 Nov 27 13:18 libcharset.so.1 -> libcharset.so.1.0.0
-rwxr-xr-x  1 root root    10312 Nov 15 00:40 libcharset.so.1.0.0
lrwxrwxrwx  1 root root       18 Nov 27 13:18 libcrypto.so -> libcrypto.so.1.0.0
-r-xr-xr-x  1 root root  2402992 Nov 15 00:40 libcrypto.so.1.0.0
lrwxrwxrwx  1 root root       14 Nov 27 13:18 libct.so -> libct.so.4.0.0
lrwxrwxrwx  1 root root       14 Nov 27 13:18 libct.so.4 -> libct.so.4.0.0
-rwxr-xr-x  1 root root   387888 Nov 15 00:40 libct.so.4.0.0
lrwxrwxrwx  1 root root       16 Nov 27 13:18 libcurl.so -> libcurl.so.4.4.0
lrwxrwxrwx  1 root root       16 Nov 27 13:18 libcurl.so.4 -> libcurl.so.4.4.0
-rwxr-xr-x  1 root root   482736 Nov 15 00:40 libcurl.so.4.4.0
lrwxrwxrwx  1 root root       17 Nov 27 13:18 libexpat.so -> libexpat.so.1.5.2
lrwxrwxrwx  1 root root       17 Nov 27 13:18 libexpat.so.1 -> libexpat.so.1.5.2
-rwxr-xr-x  1 root root   198736 Nov 15 00:41 libexpat.so.1.5.2
lrwxrwxrwx  1 root root       18 Nov 27 13:18 libexslt.so -> libexslt.so.0.8.17
lrwxrwxrwx  1 root root       18 Nov 27 13:18 libexslt.so.0 -> libexslt.so.0.8.17
-rwxr-xr-x  1 root root    81008 Nov 15 00:41 libexslt.so.0.8.17
lrwxrwxrwx  1 root root       12 Nov 27 13:18 libform.so -> libform.so.5
lrwxrwxrwx  1 root root       14 Nov 27 13:18 libform.so.5 -> libform.so.5.9
-rwxr-xr-x  1 root root    69304 Nov 15 00:41 libform.so.5.9
lrwxrwxrwx  1 root root       20 Nov 27 13:18 libfreetype.so -> libfreetype.so.6.8.0
lrwxrwxrwx  1 root root       20 Nov 27 13:18 libfreetype.so.6 -> libfreetype.so.6.8.0
-rwxr-xr-x  1 root root   659000 Nov 15 00:40 libfreetype.so.6.8.0
lrwxrwxrwx  1 root root       16 Nov 27 13:18 libgdbm.so -> libgdbm.so.3.0.0
lrwxrwxrwx  1 root root       16 Nov 27 13:18 libgdbm.so.3 -> libgdbm.so.3.0.0
-rwxr-xr-x  1 root root    26960 Nov 15 00:40 libgdbm.so.3.0.0
lrwxrwxrwx  1 root root       14 Nov 27 13:18 libgd.so -> libgd.so.2.0.0
lrwxrwxrwx  1 root root       14 Nov 27 13:18 libgd.so.2 -> libgd.so.2.0.0
-rwxr-xr-x  1 root root   279264 Nov 15 00:40 libgd.so.2.0.0
-rwxr-xr-x  1 root root  1905584 Nov 15 00:40 libgettextlib-0.19.8.1.so
lrwxrwxrwx  1 root root       25 Nov 27 13:18 libgettextlib.so -> libgettextlib-0.19.8.1.so
lrwxrwxrwx  1 root root       21 Nov 27 13:18 libgettextpo.so -> libgettextpo.so.0.5.4
lrwxrwxrwx  1 root root       21 Nov 27 13:18 libgettextpo.so.0 -> libgettextpo.so.0.5.4
-rwxr-xr-x  1 root root   420888 Nov 15 00:41 libgettextpo.so.0.5.4
-rwxr-xr-x  1 root root   368232 Nov 15 00:40 libgettextsrc-0.19.8.1.so
lrwxrwxrwx  1 root root       25 Nov 27 13:18 libgettextsrc.so -> libgettextsrc-0.19.8.1.so
lrwxrwxrwx  1 root root       17 Nov 27 13:18 libiconv.so -> libiconv.so.2.6.0
lrwxrwxrwx  1 root root       17 Nov 27 13:18 libiconv.so.2 -> libiconv.so.2.6.0
-rwxr-xr-x  1 root root   952496 Nov 15 00:41 libiconv.so.2.6.0
lrwxrwxrwx  1 root root       20 Nov 27 13:18 libicudata.so -> libicudata.so.48.1.1
lrwxrwxrwx  1 root root       20 Nov 27 13:18 libicudata.so.48 -> libicudata.so.48.1.1
-rw-r--r--  1 root root 18281112 Nov 15 00:41 libicudata.so.48.1.1
lrwxrwxrwx  1 root root       20 Nov 27 13:18 libicui18n.so -> libicui18n.so.48.1.1
lrwxrwxrwx  1 root root       20 Nov 27 13:18 libicui18n.so.48 -> libicui18n.so.48.1.1
-rwxr-xr-x  1 root root  2009992 Nov 15 00:39 libicui18n.so.48.1.1
lrwxrwxrwx  1 root root       18 Nov 27 13:18 libicuio.so -> libicuio.so.48.1.1
lrwxrwxrwx  1 root root       18 Nov 27 13:18 libicuio.so.48 -> libicuio.so.48.1.1
-rwxr-xr-x  1 root root    55768 Nov 15 00:41 libicuio.so.48.1.1
lrwxrwxrwx  1 root root       18 Nov 27 13:18 libicule.so -> libicule.so.48.1.1
lrwxrwxrwx  1 root root       18 Nov 27 13:18 libicule.so.48 -> libicule.so.48.1.1
-rwxr-xr-x  1 root root   227520 Nov 15 00:40 libicule.so.48.1.1
lrwxrwxrwx  1 root root       18 Nov 27 13:18 libiculx.so -> libiculx.so.48.1.1
lrwxrwxrwx  1 root root       18 Nov 27 13:18 libiculx.so.48 -> libiculx.so.48.1.1
-rwxr-xr-x  1 root root    51592 Nov 15 00:41 libiculx.so.48.1.1
lrwxrwxrwx  1 root root       20 Nov 27 13:18 libicutest.so -> libicutest.so.48.1.1
lrwxrwxrwx  1 root root       20 Nov 27 13:18 libicutest.so.48 -> libicutest.so.48.1.1
-rwxr-xr-x  1 root root    82168 Nov 15 00:41 libicutest.so.48.1.1
lrwxrwxrwx  1 root root       18 Nov 27 13:18 libicutu.so -> libicutu.so.48.1.1
lrwxrwxrwx  1 root root       18 Nov 27 13:18 libicutu.so.48 -> libicutu.so.48.1.1
-rwxr-xr-x  1 root root   155752 Nov 15 00:40 libicutu.so.48.1.1
lrwxrwxrwx  1 root root       18 Nov 27 13:18 libicuuc.so -> libicuuc.so.48.1.1
lrwxrwxrwx  1 root root       18 Nov 27 13:18 libicuuc.so.48 -> libicuuc.so.48.1.1
-rwxr-xr-x  1 root root  1612536 Nov 15 00:40 libicuuc.so.48.1.1
lrwxrwxrwx  1 root root       16 Nov 27 13:18 libjpeg.so -> libjpeg.so.8.4.0
lrwxrwxrwx  1 root root       16 Nov 27 13:18 libjpeg.so.8 -> libjpeg.so.8.4.0
-rwxr-xr-x  1 root root   289320 Nov 15 00:40 libjpeg.so.8.4.0
lrwxrwxrwx  1 root root       20 Nov 27 13:18 liblber-2.4.so.2 -> liblber-2.4.so.2.5.4
-rw-r--r--  1 root root    60464 Nov 15 00:40 liblber-2.4.so.2.5.4
lrwxrwxrwx  1 root root       20 Nov 27 13:18 liblber.so -> liblber-2.4.so.2.5.4
lrwxrwxrwx  1 root root       20 Nov 27 13:18 libldap-2.4.so.2 -> libldap-2.4.so.2.5.4
-rw-r--r--  1 root root   289168 Nov 15 00:40 libldap-2.4.so.2.5.4
lrwxrwxrwx  1 root root       22 Nov 27 13:18 libldap_r-2.4.so.2 -> libldap_r-2.4.so.2.5.4
-rw-r--r--  1 root root   314288 Nov 15 00:40 libldap_r-2.4.so.2.5.4
lrwxrwxrwx  1 root root       22 Nov 27 13:18 libldap_r.so -> libldap_r-2.4.so.2.5.4
lrwxrwxrwx  1 root root       20 Nov 27 13:18 libldap.so -> libldap-2.4.so.2.5.4
lrwxrwxrwx  1 root root       16 Nov 27 13:18 libltdl.so -> libltdl.so.3.1.0
lrwxrwxrwx  1 root root       16 Nov 27 13:18 libltdl.so.3 -> libltdl.so.3.1.0
-rwxr-xr-x  1 root root    35288 Nov 15 00:40 libltdl.so.3.1.0
drwxr-xr-x  2 root root     4096 Nov 27 13:17 libmcrypt
lrwxrwxrwx  1 root root       18 Nov 27 13:18 libmcrypt.so -> libmcrypt.so.4.4.8
lrwxrwxrwx  1 root root       18 Nov 27 13:18 libmcrypt.so.4 -> libmcrypt.so.4.4.8
-rwxr-xr-x  1 root root   220544 Nov 15 00:40 libmcrypt.so.4.4.8
lrwxrwxrwx  1 root root       12 Nov 27 13:18 libmenu.so -> libmenu.so.5
lrwxrwxrwx  1 root root       14 Nov 27 13:18 libmenu.so.5 -> libmenu.so.5.9
-rwxr-xr-x  1 root root    31416 Nov 15 00:40 libmenu.so.5.9
lrwxrwxrwx  1 root root       17 Nov 27 13:18 libmhash.so -> libmhash.so.2.0.1
lrwxrwxrwx  1 root root       17 Nov 27 13:18 libmhash.so.2 -> libmhash.so.2.0.1
-rwxr-xr-x  1 root root   199000 Nov 15 00:41 libmhash.so.2.0.1
lrwxrwxrwx  1 root root       16 Nov 27 13:18 libming.so -> libming.so.1.4.4
lrwxrwxrwx  1 root root       16 Nov 27 13:18 libming.so.1 -> libming.so.1.4.4
-rwxr-xr-x  1 root root   457424 Nov 15 00:40 libming.so.1.4.4
lrwxrwxrwx  1 root root       17 Nov 27 13:18 libmysqlclient_r.so -> libmysqlclient.so
lrwxrwxrwx  1 root root       17 Nov 27 13:18 libmysqlclient_r.so.18 -> libmysqlclient.so
lrwxrwxrwx  1 root root       17 Nov 27 13:18 libmysqlclient_r.so.18.0.0 -> libmysqlclient.so
lrwxrwxrwx  1 root root       20 Nov 27 13:18 libmysqlclient.so -> libmysqlclient.so.18
lrwxrwxrwx  1 root root       24 Nov 27 13:18 libmysqlclient.so.18 -> libmysqlclient.so.18.0.0
-rwxr-xr-x  1 root root  3839456 Nov 15 00:41 libmysqlclient.so.18.0.0
lrwxrwxrwx  1 root root       15 Nov 27 13:18 libncurses.so -> libncurses.so.5
lrwxrwxrwx  1 root root       17 Nov 27 13:18 libncurses.so.5 -> libncurses.so.5.9
-rwxr-xr-x  1 root root   374432 Nov 15 00:41 libncurses.so.5.9
lrwxrwxrwx  1 root root       21 Nov 27 13:18 libnghttp2.so -> libnghttp2.so.14.12.3
lrwxrwxrwx  1 root root       21 Nov 27 13:18 libnghttp2.so.14 -> libnghttp2.so.14.12.3
-rwxr-xr-x  1 root root   190504 Nov 15 00:40 libnghttp2.so.14.12.3
lrwxrwxrwx  1 root root       13 Nov 27 13:18 libpanel.so -> libpanel.so.5
lrwxrwxrwx  1 root root       15 Nov 27 13:18 libpanel.so.5 -> libpanel.so.5.9
-rwxr-xr-x  1 root root    14264 Nov 15 00:39 libpanel.so.5.9
lrwxrwxrwx  1 root root       21 Nov 27 13:18 libpcreposix.so -> libpcreposix.so.0.0.4
lrwxrwxrwx  1 root root       21 Nov 27 13:18 libpcreposix.so.0 -> libpcreposix.so.0.0.4
-rwxr-xr-x  1 root root    10240 Nov 15 00:39 libpcreposix.so.0.0.4
lrwxrwxrwx  1 root root       16 Nov 27 13:18 libpcre.so -> libpcre.so.1.2.8
lrwxrwxrwx  1 root root       16 Nov 27 13:18 libpcre.so.1 -> libpcre.so.1.2.8
-rwxr-xr-x  1 root root   276656 Nov 15 00:40 libpcre.so.1.2.8
lrwxrwxrwx  1 root root       19 Nov 27 13:18 libpng15.so -> libpng15.so.15.26.0
lrwxrwxrwx  1 root root       19 Nov 27 13:18 libpng15.so.15 -> libpng15.so.15.26.0
-rwxr-xr-x  1 root root   195560 Nov 15 00:40 libpng15.so.15.26.0
lrwxrwxrwx  1 root root       11 Nov 27 13:18 libpng.so -> libpng15.so
lrwxrwxrwx  1 root root       12 Nov 27 13:18 libpq.so -> libpq.so.5.5
lrwxrwxrwx  1 root root       12 Nov 27 13:18 libpq.so.5 -> libpq.so.5.5
-rwxr-xr-x  1 root root   188384 Nov 15 00:39 libpq.so.5.5
lrwxrwxrwx  1 root root       20 Nov 27 13:18 libsablot.so -> libsablot.so.0.100.3
lrwxrwxrwx  1 root root       20 Nov 27 13:18 libsablot.so.0 -> libsablot.so.0.100.3
-rwxr-xr-x  1 root root   788344 Nov 15 00:40 libsablot.so.0.100.3
lrwxrwxrwx  1 root root       19 Nov 27 13:18 libsqlite3.so -> libsqlite3.so.0.8.6
lrwxrwxrwx  1 root root       19 Nov 27 13:18 libsqlite3.so.0 -> libsqlite3.so.0.8.6
-rwxr-xr-x  1 root root   952544 Nov 15 00:40 libsqlite3.so.0.8.6
lrwxrwxrwx  1 root root       18 Nov 27 13:18 libsqlite.so -> libsqlite.so.0.8.6
lrwxrwxrwx  1 root root       18 Nov 27 13:18 libsqlite.so.0 -> libsqlite.so.0.8.6
-rwxr-xr-x  1 root root   412608 Nov 15 00:41 libsqlite.so.0.8.6
lrwxrwxrwx  1 root root       15 Nov 27 13:18 libssl.so -> libssl.so.1.0.0
-r-xr-xr-x  1 root root   465168 Nov 15 00:40 libssl.so.1.0.0
lrwxrwxrwx  1 root root       19 Nov 27 13:18 libstdc++.so.6 -> libstdc++.so.6.0.19
-rwxr-xr-x  1 root root   999936 Nov 15 00:41 libstdc++.so.6.0.19
lrwxrwxrwx  1 root root       17 Nov 27 13:18 libsybdb.so -> libsybdb.so.5.0.0
lrwxrwxrwx  1 root root       17 Nov 27 13:18 libsybdb.so.5 -> libsybdb.so.5.0.0
-rwxr-xr-x  1 root root   458336 Nov 15 00:40 libsybdb.so.5.0.0
lrwxrwxrwx  1 root root       16 Nov 27 13:18 libtiff.so -> libtiff.so.5.0.6
lrwxrwxrwx  1 root root       16 Nov 27 13:18 libtiff.so.5 -> libtiff.so.5.0.6
-rwxr-xr-x  1 root root   463896 Nov 15 00:40 libtiff.so.5.0.6
lrwxrwxrwx  1 root root       18 Nov 27 13:18 libtiffxx.so -> libtiffxx.so.5.0.6
lrwxrwxrwx  1 root root       18 Nov 27 13:18 libtiffxx.so.5 -> libtiffxx.so.5.0.6
-rwxr-xr-x  1 root root    10304 Nov 15 00:40 libtiffxx.so.5.0.6
lrwxrwxrwx  1 root root       16 Nov 27 13:18 libxml2.so -> libxml2.so.2.9.4
lrwxrwxrwx  1 root root       16 Nov 27 13:18 libxml2.so.2 -> libxml2.so.2.9.4
-rwxr-xr-x  1 root root  1913744 Nov 15 00:40 libxml2.so.2.9.4
drwxr-xr-x  2 root root     4096 Nov 27 13:17 libxslt-plugins
lrwxrwxrwx  1 root root       17 Nov 27 13:18 libxslt.so -> libxslt.so.1.1.29
lrwxrwxrwx  1 root root       17 Nov 27 13:18 libxslt.so.1 -> libxslt.so.1.1.29
-rwxr-xr-x  1 root root   287904 Nov 15 00:40 libxslt.so.1.1.29
lrwxrwxrwx  1 root root       14 Nov 27 13:18 libz.so -> libz.so.1.2.11
lrwxrwxrwx  1 root root       14 Nov 27 13:18 libz.so.1 -> libz.so.1.2.11
-rwxr-xr-x  1 root root   108904 Nov 15 00:40 libz.so.1.2.11
lrwxrwxrwx  1 root root       15 Nov 27 13:18 libzzip-0.so.10 -> libzzip-0.so.13
lrwxrwxrwx  1 root root       15 Nov 27 13:18 libzzip-0.so.11 -> libzzip-0.so.13
lrwxrwxrwx  1 root root       15 Nov 27 13:18 libzzip-0.so.12 -> libzzip-0.so.13
lrwxrwxrwx  1 root root       20 Nov 27 13:18 libzzip-0.so.13 -> libzzip-0.so.13.0.62
-rwxr-xr-x  1 root root    31664 Nov 15 00:40 libzzip-0.so.13.0.62
lrwxrwxrwx  1 root root       21 Nov 27 13:18 libzzipfseeko-0.so.10 -> libzzipfseeko-0.so.13
lrwxrwxrwx  1 root root       21 Nov 27 13:18 libzzipfseeko-0.so.11 -> libzzipfseeko-0.so.13
lrwxrwxrwx  1 root root       21 Nov 27 13:18 libzzipfseeko-0.so.12 -> libzzipfseeko-0.so.13
lrwxrwxrwx  1 root root       26 Nov 27 13:18 libzzipfseeko-0.so.13 -> libzzipfseeko-0.so.13.0.62
-rwxr-xr-x  1 root root    14416 Nov 15 00:40 libzzipfseeko-0.so.13.0.62
lrwxrwxrwx  1 root root       26 Nov 27 13:18 libzzipfseeko.so -> libzzipfseeko-0.so.13.0.62
lrwxrwxrwx  1 root root       22 Nov 27 13:18 libzzipmmapped-0.so.10 -> libzzipmmapped-0.so.13
lrwxrwxrwx  1 root root       22 Nov 27 13:18 libzzipmmapped-0.so.11 -> libzzipmmapped-0.so.13
lrwxrwxrwx  1 root root       22 Nov 27 13:18 libzzipmmapped-0.so.12 -> libzzipmmapped-0.so.13
lrwxrwxrwx  1 root root       27 Nov 27 13:18 libzzipmmapped-0.so.13 -> libzzipmmapped-0.so.13.0.62
-rwxr-xr-x  1 root root    18712 Nov 15 00:40 libzzipmmapped-0.so.13.0.62
lrwxrwxrwx  1 root root       27 Nov 27 13:18 libzzipmmapped.so -> libzzipmmapped-0.so.13.0.62
lrwxrwxrwx  1 root root       20 Nov 27 13:18 libzzip.so -> libzzip-0.so.13.0.62
lrwxrwxrwx  1 root root       24 Nov 27 13:18 libzzipwrap-0.so.13 -> libzzipwrap-0.so.13.0.62
-rwxr-xr-x  1 root root    10248 Nov 15 00:41 libzzipwrap-0.so.13.0.62
lrwxrwxrwx  1 root root       24 Nov 27 13:18 libzzipwrap.so -> libzzipwrap-0.so.13.0.62
drwxr-xr-x  3 root root     4096 Nov 27 13:17 mysql
drwxr-xr-x  4 root root     4096 Nov 27 13:17 perl5
drwxr-xr-x 47 root root     4096 Nov 27 13:17 php
drwxr-xr-x  2 root root     4096 Nov 27 13:18 pkgconfig
-rw-r--r--  1 root root   944224 Nov 15 00:39 preloadable_libiconv.so
-rw-r--r--  1 root root    43672 Nov 15 00:39 preloadable_libintl.so
drwxr-xr-x  2 root root     4096 Nov 27 13:17 proftpd
lrwxrwxrwx  1 root root       17 Nov 27 13:18 terminfo -> ../share/terminfo
-rw-r--r--  1 root root        8 Nov 27 13:18 VERSION
-rw-r--r--  1 root root      222 Nov 15 00:09 xml2Conf.sh
-rw-r--r--  1 root root      221 Nov 15 00:09 xsltConf.sh

**Comment by selwynorren** [comment]
Just for further info, if I write whereis php, it returns the following:
php: /opt/lampp/bin/php

if I enter /opt/lampp/bin/php as the path locator, I still get the notification that php cannot be found

**Comment by bartzaalberg** [comment]
No you should enter /opt/lamp/bin. Because its possible you have multiple PHP versions in there, and they will both be loaded so you can switch on the go.

But i think i found the issue. My php executables are called php5.5 and php7. Could you try to rename your php file to php with a number on the end like php7? If that works you could just change it back.

**Comment by bartzaalberg** [comment]
No the output seems correct.
But just to be clear you set the php path to  /opt/lampp/bin/
And you have the file like this ? /opt/lampp/bin/php7?

**Comment by selwynorren** [comment]
100% correct

**Comment by bartzaalberg** [comment]
hmm.. that's odd. I will install lampp tonight and see what i can find.

**Comment by selwynorren** [comment]
Thanks so much, really appreciate all your help. P.S I am using apache and friends' xampp

**Comment by dignityinside** [comment]
Thank for adding this cool Setting, but with Xampp (PHP 7.2.13) this does not work for me to.

I tryed:
- /opt/lampp/bin/php
- /opt/lampp/bin/
- /opt/lampp/bin
- /usr/bin/php
- /usr/bin/
- /usr/bin

**Comment by bartzaalberg** [comment]
Ok, so i've found the issue. The location lamp installed is not accessible by the application. Its also not the default location PHP is installed. As a workaround,  you can run the following command the create a symlink. 

`sudo ln -s /opt/lampp/bin/php /usr/bin/php`


This will create a link from /usr/bin/php to your lampp php. Then also an update is necessary to find php executables without a version number at the end. I just added that to master. RRelease will be elease will be later today. I'm sorry you still have to run a command to use my application. But i can't really find a simpler way right now.

**Comment by bartzaalberg** [comment]
Its been released. Can you test?

**Comment by dignityinside** [comment]
Now it's work! Thank you.

My Setting: "/usr/bin/"

**Comment by bartzaalberg** [comment]
Ok, closing this!

**Comment by selwynorren** [comment]
Beautiful, could we perhaps include the symlink creation as part of the instruction on the read.me?

Works very well by the way, thanks very much

**Comment by bartzaalberg** [comment]
Actually i already added a FAQ at the bottom of the README with the symlink :)

**Comment by selwynorren** [comment]
Ha ha ha, you did indeed, sorry I typed that without even checking the read.me first,. sorry about that. Again, thanks so much for all your efforts. Love your app. Honestly your app and Ciano are the two main reasons why I moved to Elementary OS

**Comment by bartzaalberg** [comment]
Thnx! Let me know if you find any other problems or have feature requests!

**Comment by selwynorren** [comment]
Thanks so much, for now I will be playing with it and seeing how it goes.
