### ISSUE TITLE
Consider using gtksourceview for the code pane

### ISSUE THREAD

**Issue by grvrulz** [bartzaalberg/php-tester#4]
What it says in the title. This will open doors to improvements like showing line numbers, setting a background color(or theme).

**Comment by bartzaalberg** [comment]
Will definitly try that!

Op 9 okt. 2017 10:57 schreef Gaurav Pareek <notifications@github.com>:

What it says in the title. This will open doors to improvements like showing line numbers, setting a background color(or theme).

**Comment by bartzaalberg** [comment]
Added this to release 1.1.0
