### ISSUE TITLE
Copy result?

### ISSUE THREAD

**Issue by gravitano** [bartzaalberg/php-tester#6]
Hi,

Can you add ability to copy the result?

Thanks!

**Comment by bartzaalberg** [comment]
Added it to next release

**Comment by gravitano** [comment]
Hey @bartzaalberg,

Thank you for the geat work. What i mean is ability to copy the **RESULT**. Copying the code is also good feature. But, I need to copy the result.

For example, say you have this code:
```php
<?php

echo json_encode([
	"foo" => "bar"
]);
```

And the result just:
```
{"foo": "bar"}
```
I want to copy my json result. **NOT** the code i made. Maybe you can add a tiny title copy icon on the top of result block/view/(whatever that name is). Hope you consider it.

Thanks!

**Comment by bartzaalberg** [comment]
Whoops, i understad. Ill reopen it

**Comment by bartzaalberg** [comment]
Added it to release 1.2.1. Waiting for approval but should be released soon

**Comment by gravitano** [comment]
Thanks man :+1:
